-- MySQL Script generated by MySQL Workbench
-- lun 26 oct 2015 20:45:37 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `idCiudad` INT(4) NOT NULL COMMENT '',
  `nombreCiudad` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idCiudad`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT(5) NOT NULL COMMENT '',
  `nombreCliente` VARCHAR(45) NOT NULL COMMENT '',
  `apellidoCliente` VARCHAR(45) NOT NULL COMMENT '',
  `direccionCliente` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` INT(10) NOT NULL COMMENT '',
  `codigoCiudad` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '',
  INDEX `fk_cliente_codCiudad` (`codigoCiudad` ASC)  COMMENT '',
  CONSTRAINT `fk_cliente_codCiudad`
    FOREIGN KEY (`codigoCiudad`)
    REFERENCES `mydb`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proovedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proovedor` (
  `idProovedor` INT(5) NOT NULL COMMENT '',
  `nombreProovedor` VARCHAR(45) NOT NULL COMMENT '',
  `apellidoProovedor` VARCHAR(45) NOT NULL COMMENT '',
  `nombreComercial` VARCHAR(45) NOT NULL COMMENT '',
  `direccionProovedor` VARCHAR(45) NULL COMMENT '',
  `telefono` INT(10) NULL COMMENT '',
  `codigoCiudad` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`idProovedor`)  COMMENT '',
  INDEX `fk_proovedor_codCiudad` (`codigoCiudad` ASC)  COMMENT '',
  CONSTRAINT `fk_proovedor_codCiudad`
    FOREIGN KEY (`codigoCiudad`)
    REFERENCES `mydb`.`ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_articulo` (
  `idTipoArticulo` INT(4) NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTipoArticulo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulo` (
  `idArticulo` INT(6) NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `codigoTipoArticulo` INT(4) NOT NULL COMMENT '',
  `codigoProovedor` INT(5) NOT NULL COMMENT '',
  PRIMARY KEY (`idArticulo`)  COMMENT '',
  INDEX `fk_articulo_tipo_articulo1_idx` (`codigoTipoArticulo` ASC)  COMMENT '',
  INDEX `fk_articulo_proovedor1_idx` (`codigoProovedor` ASC)  COMMENT '',
  CONSTRAINT `fk_articulo_tipo_articulo1`
    FOREIGN KEY (`codigoTipoArticulo`)
    REFERENCES `mydb`.`tipo_articulo` (`idTipoArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_proovedor1`
    FOREIGN KEY (`codigoProovedor`)
    REFERENCES `mydb`.`proovedor` (`idProovedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `no_Factura` INT(11) NOT NULL COMMENT '',
  `codCliente` INT(5) NOT NULL COMMENT '',
  `nombreExpideFact` VARCHAR(45) NOT NULL COMMENT '',
  `fechaFact` DATE NOT NULL COMMENT '',
  `horaFact` TIME NOT NULL COMMENT '',
  `cod_FormaPago` INT NOT NULL COMMENT '',
  `subtotalFact` DECIMAL(10,0) NOT NULL COMMENT '',
  `fact_IVA` DECIMAL(10,0) NOT NULL COMMENT '',
  PRIMARY KEY (`no_Factura`)  COMMENT '',
  INDEX `fk_codCliente` (`codCliente` ASC)  COMMENT '',
  CONSTRAINT `fk_codCliente`
    FOREIGN KEY (`codCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_factura` (
  `cod_Factura` INT(11) NOT NULL COMMENT '',
  `cod_Articulo` INT(6) NOT NULL COMMENT '',
  `cantidad` INT(4) NOT NULL COMMENT '',
  `total` DECIMAL(10,0) NOT NULL COMMENT '',
  INDEX `fk_noFact` (`cod_Factura` ASC)  COMMENT '',
  INDEX `fk_idArticulo` (`cod_Articulo` ASC)  COMMENT '',
  PRIMARY KEY (`cod_Articulo`, `cod_Factura`)  COMMENT '',
  CONSTRAINT `fk_noFact`
    FOREIGN KEY (`cod_Factura`)
    REFERENCES `mydb`.`factura` (`no_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idArticulo`
    FOREIGN KEY (`cod_Articulo`)
    REFERENCES `mydb`.`articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`devolucion` (
  `cod_DetalleFact` INT(11) NOT NULL COMMENT '',
  `cod_DetalleArt` INT(6) NOT NULL COMMENT '',
  `motivo` VARCHAR(45) NOT NULL COMMENT '',
  `fechaDev` DATE NOT NULL COMMENT '',
  `horaDev` TIME NOT NULL COMMENT '',
  `cantidadDev` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`cod_DetalleFact`, `cod_DetalleArt`)  COMMENT '',
  CONSTRAINT `fk_dev_detalleFact`
    FOREIGN KEY (`cod_DetalleFact` , `cod_DetalleArt`)
    REFERENCES `mydb`.`detalle_factura` (`cod_Articulo` , `cod_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idInventario` INT(15) NOT NULL AUTO_INCREMENT COMMENT '',
  `codArticulo` INT(6) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `entrada` INT(4) NOT NULL COMMENT '',
  `salida` INT(4) NOT NULL COMMENT '',
  `existencia` INT(6) NOT NULL COMMENT '',
  `costoUnitario` DECIMAL(10,0) NOT NULL COMMENT '',
  `debe` DECIMAL(10,0) NOT NULL COMMENT '',
  `haber` DECIMAL(10,0) NOT NULL COMMENT '',
  `saldo` DECIMAL(10,0) NOT NULL COMMENT '',
  PRIMARY KEY (`idInventario`, `codArticulo`)  COMMENT '',
  INDEX `fk_idArticulo` (`codArticulo` ASC)  COMMENT '',
  CONSTRAINT `fk_idArticulo`
    FOREIGN KEY (`codArticulo`)
    REFERENCES `mydb`.`articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
